Feature/create md generator
Heydon/inclusive-design-checklist pull request #22
Opened 2017-11-29 21:07 UTC by hankchizljaw

## About this PR
I've made a little generator with node that will convert the `checklist.json` file into `README.md`. It's bare-bones ES5 to make sure it's as easy to run as possible. The only prerequisite is that the user has node installed on their machine. 

I also split the readme up by creating `intro.md`. This is so we can continue to manage the content of it in a reasonable fashion.

To run the generator,  run: `node generator/index.js`

2017-11-30 10:28 UTC, peter-mouland commented on README.md
> +- [ ] Instead of obstructing users with CAPTCHAs, use [honeypots [Resource #1](https://en.wikipedia.org/wiki/Honeypot_(computing))
seems to be an extra `[` here

2017-11-30 10:30 UTC, peter-mouland requested changes
Nice work! but looks like a couple some minor tweaks are needed (see comments)

2017-11-30 10:30 UTC, peter-mouland commented on README.md
> +- [ ] Don"t make users perform actions to reveal content unless completely necessary
not sure `"` is necessary :)

2017-11-30 10:31 UTC, hankchizljaw commented
@peter-mouland, Yeh they're all from `checklist.json`, so that could do with a tidy up :)

2017-12-02 12:56 UTC, Heydon commented
@hankchizljaw Not clear on the status of this pull request. Can I merge or are you still tweaking?

2017-12-02 14:26 UTC, hankchizljaw commented
Yeh the generator is good to go mate. I think we could tackle the pre-commit in a separate PR. 

I think we could work out how to integrate and the pre-commit as a group. I started off a bit of a discussion in #1. We should probably split out into another issue though?

2017-12-02 14:38 UTC, Heydon commented
@hankchizljaw Sounds good.

2017-12-02 14:40 UTC, merged

2017-12-02 21:27 UTC, hankchizljaw commented
I’ve started a new discussion in #23. Thanks for merging the code in, @Heydon! 🙂